version: 2
notify:
  webhooks:
    - url: https://coveralls.io/webhook?repo_token=${COVERALLS_TOKEN}
jobs:
  build:
    docker:
      - image: synqfm/circleci:0.4.0-golang
    environment:
      REPO: "SYNQ-Golang"
      SYNQ_DIR: "/go/src/github.com/SYNQfm"
    working_directory: /go/src/github.com/SYNQfm/SYNQ-Golang
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: |
            sudo chown  -R circleci:circleci "${SYNQ_DIR}"
            go get github.com/kardianos/govendor
            govendor sync
      - run:
          name: Run Golang Tests
          command: |
            GOPATH=$GOPATH:"${SYNQ_DIR}"/"${REPO}"/vendor overalls -project=github.com/SYNQfm/${REPO} -covermode=atomic -debug -ignore=.git,vendor,.circleci,cli,sample -- -race -v
            if [ -z ${COVERALLS_TOKEN} ]; then
              echo "coveralls token isn't set, skipping"
            else
              goveralls -coverprofile="${SYNQ_DIR}"/"${REPO}"/overalls.coverprofile -service circle-ci -repotoken "${COVERALLS_TOKEN}"
            fi
      - run:
          name: Build CLI
          command: |
            cd cli
            go build
